apiVersion: v1
kind: Namespace
metadata:
  name: pipeline
  
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  namespace: pipeline

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: pipeline

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-k8s-installer
  namespace: pipeline
  labels:
    app: spinnaker-k8s-installer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spinnaker-k8s-installer
  template:
    metadata:
      annotations:
        ssl-cert.tiller.default: "shared"
        ssl-cert.spin-deck: "spin-deck:spin-deck,k8s-demo"
        ssl-cert.spin-gate: "spin-gate:spin-gate,k8s-demo"
	pwd.shared: "ldap-root"
      labels:
        app: spinnaker-k8s-installer
    spec:
      serviceAccountName: pipeline
      containers:
      - name: spinnaker-k8s-installer
        image: cubeearth/spinnaker-k8s-installer:latest
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INGRESS_DNS
          value: k8s-demo
        command: [ "sh", "-c", "tail -f /dev/null" ]
