apiVersion: v1
kind: PersistentVolume
metadata:
  name: pipeline-minio-pv
  labels:
    type: local
spec:
  storageClassName: pipeline-minio
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pipeline-minio"
    
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
spec:
  storageClassName: pipeline-minio
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
